# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information, see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# The following workflow file triggers the Existing Virtual Network deployment test "test_healthcheck_existing_vnet.py" every Tuesday with platform as "Windows" in "westeurope" region.

name: MATLAB Production Server Ref Arch Azure Existing Virtual Network Health Check Test on Windows in West Eu

on:
 workflow_dispatch:
 schedule:
    - cron: '0 16 * * 2'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r ./healthcheck/requirements.txt
       
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: MPS ref Arch Existing Virtual Network Health check test on Windows in West Eu
      run: |
        cd healthcheck
        python test_healthcheck_existing_vnet.py ${{ secrets.TenantId }} ${{ secrets.ClientId }} ${{ secrets.ClientSecret }} ${{ secrets.SubscriptionId }} ${{ secrets.username }} ${{ secrets.password }} ${{ secrets.ipaddress }} ${{ secrets.base64certdata }} ${{ secrets.base64password }} "westeurope" "Windows"
